version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '3000:3001'
      - '9229:9229'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres: